swagger: '2.0'
info:
  description: Description
  version: v1
  title: Rest API with Flask
  contact:
    name: Julio Cesar
    email: julio@blackdevs.com.br

tags:
  - name: Health
    description: Health Check
  - name: Stocks
    description: Stocks Resource

paths:
  /api/healthcheck:
    get:
      tags:
        - Health
      summary: Get health
      operationId: getHealth
      produces:
        - application/json
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error

  /api/stocks/last:
    get:
      tags:
        - Stocks
      summary: Get last stocks
      operationId: getLastStocks
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Stock'
        '500':
          description: Internal Server Error

  /api/stocks/last/{name}:
    get:
      tags:
        - Stocks
      summary: Get last stock by Name
      operationId: getLastStockByName
      produces:
        - application/json
      parameters:
        - name: name
          in: path
          description: Name
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Stock'
        '500':
          description: Internal Server Error

  /api/stocks/{country}/last:
    get:
      tags:
        - Stocks
      summary: Get last stocks by Country
      operationId: getLastStocksByCountry
      produces:
        - application/json
      parameters:
        - name: country
          in: path
          description: Country
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Stock'
        '500':
          description: Internal Server Error

  /api/stocks/{country}/last/{name}:
    get:
      tags:
        - Stocks
      summary: Get last stock by Country and Name
      operationId: getLastStockByCountryAndName
      produces:
        - application/json
      parameters:
        - name: country
          in: path
          description: Country
          required: true
          type: string
        - name: name
          in: path
          description: Name
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Stock'
        '500':
          description: Internal Server Error

definitions:
  Stock:
    type: object
    properties:
      status:
        type: string
        example: 'OK'
      id:
        type: string
        example: 'UUID'
      name:
        type: string
        example: 'itub4'
      country:
        type: string
        example: 'brazil'
      price:
        type: number
        example: 0.00
      date:
        type: string
        format: date-time
        example: '2021-01-01T00:00:00.000Z'
